version: '3.7'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    restart: unless-stopped
    entrypoint: ./docker/backend/wsgi-entrypoint.sh
    expose:
      - "8000"
    volumes:
      - static_value:./backend/static/
      - media_value:./backend/media/
    depends_on:
      - db
    env_file:
      - ./backend/.env

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/development/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:./backend/static/
      - media_value:./backend/media/

    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
